-- Sections step 5: every existing section converted to the new names.
--
-- GENERATED by scripts/make-section-conversion-sql.mjs from the list
-- Heinrich approved (docs/SECTION-CONVERSION-LIST.md, 16-17 Sep 2026).
-- Do not edit by hand: change the script and run it again.
--
-- Renames each section in Stock Manager and every copy of its name:
-- structural stock lines, requisitions (name and label), cut lists,
-- quote and BOM parts, reservations, the usage log, tube section aliases,
-- laser programs and tube job lines (these three start with the section,
-- then the material). Fills in each section's type and numbers, merges
-- the rows that become one (keeping the larger kg/m and R/m), deletes the
-- cut-off "Round Tube 42mm x 1.", adds CH 120x55, and sets the Section
-- Types list to the fixed 18. Old purchase orders are history: untouched.
--
-- Safe to run twice: a second run finds no old names left.
-- Paste each PART on its own, in order: practice first, then live.
-- Best run when nobody has Stock Manager open; refresh the app afterwards.

-- ============ PART 1 ============
create table if not exists public.section_rename_map (old text primary key, new text not null, type text not null, dims jsonb not null);
-- No rules: the app never reads it, only this SQL (run as the owner) does.
alter table public.section_rename_map enable row level security;

insert into public.section_rename_map (old, new, type, dims) values
  ('SHS 25X25X1.9', 'SHS 25x25x1.9', 'Square Tube', '{"shape":"SHS","a":25,"t":1.9}'::jsonb),
  ('SHS 30x30x3mm', 'SHS 30x30x3', 'Square Tube', '{"shape":"SHS","a":30,"t":3}'::jsonb),
  ('SHS 32x32x2mm', 'SHS 32x32x2', 'Square Tube', '{"shape":"SHS","a":32,"t":2}'::jsonb),
  ('SHS 32x32x3mm', 'SHS 32x32x3', 'Square Tube', '{"shape":"SHS","a":32,"t":3}'::jsonb),
  ('SHS 38.1x38.1x1.6', 'SHS 38.1x38.1x1.6', 'Square Tube', '{"shape":"SHS","a":38.1,"t":1.6}'::jsonb),
  ('38.10*1.60*3250mm', 'SHS 38.1x38.1x1.6', 'Square Tube', '{"shape":"SHS","a":38.1,"t":1.6}'::jsonb),
  ('38.10*1.60*3300mm', 'SHS 38.1x38.1x1.6', 'Square Tube', '{"shape":"SHS","a":38.1,"t":1.6}'::jsonb),
  ('SHS 38.1x38.1x2mm', 'SHS 38.1x38.1x2', 'Square Tube', '{"shape":"SHS","a":38.1,"t":2}'::jsonb),
  ('SHS 40x40x3mm', 'SHS 40x40x3', 'Square Tube', '{"shape":"SHS","a":40,"t":3}'::jsonb),
  ('50x50x1.5', 'SHS 50x50x1.5', 'Square Tube', '{"shape":"SHS","a":50,"t":1.5}'::jsonb),
  ('SHS 50x50x1.5mm', 'SHS 50x50x1.5', 'Square Tube', '{"shape":"SHS","a":50,"t":1.5}'::jsonb),
  ('50x50x2', 'SHS 50x50x2', 'Square Tube', '{"shape":"SHS","a":50,"t":2}'::jsonb),
  ('SHS 50x50x2mm', 'SHS 50x50x2', 'Square Tube', '{"shape":"SHS","a":50,"t":2}'::jsonb),
  ('SHS 50x50x3mm', 'SHS 50x50x3', 'Square Tube', '{"shape":"SHS","a":50,"t":3}'::jsonb),
  ('SHS 76x76x2mm', 'SHS 76.2x76.2x2', 'Square Tube', '{"shape":"SHS","a":76.2,"t":2}'::jsonb),
  ('SHS 76.2x76.2x2mm', 'SHS 76.2x76.2x2', 'Square Tube', '{"shape":"SHS","a":76.2,"t":2}'::jsonb),
  ('SHS 100x100x2mm', 'SHS 100x100x2', 'Square Tube', '{"shape":"SHS","a":100,"t":2}'::jsonb),
  ('RHS 50x25x2mm', 'RHS 50x25x2', 'Rectangular Tube', '{"shape":"RHS","a":50,"b":25,"t":2}'::jsonb),
  ('RHS 60x30x3mm', 'RHS 60x30x3', 'Rectangular Tube', '{"shape":"RHS","a":60,"b":30,"t":3}'::jsonb),
  ('RHS 76x38x1.9mm', 'RHS 76.2x38.1x1.9', 'Rectangular Tube', '{"shape":"RHS","a":76.2,"b":38.1,"t":1.9}'::jsonb),
  ('RHS 76x50x1.9mm', 'RHS 76.2x50.8x1.9', 'Rectangular Tube', '{"shape":"RHS","a":76.2,"b":50.8,"t":1.9}'::jsonb),
  ('76X50X1.9mm', 'RHS 76.2x50.8x1.9', 'Rectangular Tube', '{"shape":"RHS","a":76.2,"b":50.8,"t":1.9}'::jsonb),
  ('RHS 76.2x50.8x2mm', 'RHS 76.2x50.8x2', 'Rectangular Tube', '{"shape":"RHS","a":76.2,"b":50.8,"t":2}'::jsonb),
  ('RHS 76x50x4.5mm', 'RHS 76.2x50.8x4.5', 'Rectangular Tube', '{"shape":"RHS","a":76.2,"b":50.8,"t":4.5}'::jsonb),
  ('RHS 80x40x3.6mm', 'RHS 80x40x3.6', 'Rectangular Tube', '{"shape":"RHS","a":80,"b":40,"t":3.6}'::jsonb),
  ('100x50x2', 'RHS 100x50x2', 'Rectangular Tube', '{"shape":"RHS","a":100,"b":50,"t":2}'::jsonb),
  ('RHS 100x50x2mm', 'RHS 100x50x2', 'Rectangular Tube', '{"shape":"RHS","a":100,"b":50,"t":2}'::jsonb),
  ('RHS 150x50x2mm', 'RHS 150x50x2', 'Rectangular Tube', '{"shape":"RHS","a":150,"b":50,"t":2}'::jsonb),
  ('Round Tube 19mm x 2mm wall', 'CHS 19.05x2', 'Round Tube', '{"shape":"CHS","od":19.05,"t":2}'::jsonb),
  ('Round Tube 19.05mm x 1.5mm wall', 'CHS 19.05x1.5', 'Round Tube', '{"shape":"CHS","od":19.05,"t":1.5}'::jsonb),
  ('Round Tube 22.2mm x 1.2mm wall', 'CHS 22.2x1.2', 'Round Tube', '{"shape":"CHS","od":22.2,"t":1.2}'::jsonb),
  ('Round Tube 25mm x 2mm wall', 'CHS 25x2', 'Round Tube', '{"shape":"CHS","od":25,"t":2}'::jsonb),
  ('Round Tube 34mm x1.5mm wall', 'CHS 34x1.5', 'Round Tube', '{"shape":"CHS","od":34,"t":1.5}'::jsonb),
  ('Round Tube 38.1mm X 1.2mm wall', 'CHS 38.1x1.2', 'Round Tube', '{"shape":"CHS","od":38.1,"t":1.2}'::jsonb)
on conflict (old) do update set new = excluded.new, type = excluded.type, dims = excluded.dims;

-- ============ PART 2 ============
insert into public.section_rename_map (old, new, type, dims) values
  ('Round Tube 38.1mm x 1.5mm wall', 'CHS 38.1x1.5', 'Round Tube', '{"shape":"CHS","od":38.1,"t":1.5}'::jsonb),
  ('Round Tube 38.1mm x 1.6mm wall', 'CHS 38.1x1.6', 'Round Tube', '{"shape":"CHS","od":38.1,"t":1.6}'::jsonb),
  ('Round Tube 38.1mm x 2mm wall', 'CHS 38.1x2', 'Round Tube', '{"shape":"CHS","od":38.1,"t":2}'::jsonb),
  ('Round Tube 38.1mm x 3.18mm wall', 'CHS 38.1x3.18', 'Round Tube', '{"shape":"CHS","od":38.1,"t":3.18}'::jsonb),
  ('Round Tube 41.27mm x 1.2mm wall', 'CHS 41.27x1.2', 'Round Tube', '{"shape":"CHS","od":41.27,"t":1.2}'::jsonb),
  ('Round Tube 42mm x1.5mm wall', 'CHS 42x1.5', 'Round Tube', '{"shape":"CHS","od":42,"t":1.5}'::jsonb),
  ('Round Tube 48.4 X 3.5mm wall', 'CHS 48.4x3.5', 'Round Tube', '{"shape":"CHS","od":48.4,"t":3.5}'::jsonb),
  ('48.4x3.5', 'CHS 48.4x3.5', 'Round Tube', '{"shape":"CHS","od":48.4,"t":3.5}'::jsonb),
  ('GRIT ROUND TUBE 50.8mm x 1.2mm', 'CHS 50.8x1.2', 'Round Tube', '{"shape":"CHS","od":50.8,"t":1.2}'::jsonb),
  ('Round Tube 57mm x 1.5mm wall', 'CHS 57x1.5', 'Round Tube', '{"shape":"CHS","od":57,"t":1.5}'::jsonb),
  ('Round Tube 57mm x 1.9mm wall', 'CHS 57x1.9', 'Round Tube', '{"shape":"CHS","od":57,"t":1.9}'::jsonb),
  ('Round Tube 63.5mm x 4mm wall', 'CHS 63.5x4', 'Round Tube', '{"shape":"CHS","od":63.5,"t":4}'::jsonb),
  ('Round Tube 76.2mm x 2mm wall', 'CHS 76.2x2', 'Round Tube', '{"shape":"CHS","od":76.2,"t":2}'::jsonb),
  ('88.9 X 2.5mm', 'CHS 88.9x2.5', 'Round Tube', '{"shape":"CHS","od":88.9,"t":2.5}'::jsonb),
  ('Round Tube 88.9 X 2.5mm wall', 'CHS 88.9x2.5', 'Round Tube', '{"shape":"CHS","od":88.9,"t":2.5}'::jsonb),
  ('Round Tube 88.9mm x 2mm wall', 'CHS 88.9x2', 'Round Tube', '{"shape":"CHS","od":88.9,"t":2}'::jsonb),
  ('Round Tube 152mm x 3mm wall', 'CHS 152x3', 'Round Tube', '{"shape":"CHS","od":152,"t":3}'::jsonb),
  ('Round Bar 5mm', 'RB 5', 'Round Bar', '{"shape":"RB","a":5}'::jsonb),
  ('Round Bar 6mm', 'RB 6', 'Round Bar', '{"shape":"RB","a":6}'::jsonb),
  ('Round Bar 8mm', 'RB 8', 'Round Bar', '{"shape":"RB","a":8}'::jsonb),
  ('Round Bar 10mm', 'RB 10', 'Round Bar', '{"shape":"RB","a":10}'::jsonb),
  ('Round Bar 12mm', 'RB 12', 'Round Bar', '{"shape":"RB","a":12}'::jsonb),
  ('Round Bar 16mm', 'RB 16', 'Round Bar', '{"shape":"RB","a":16}'::jsonb),
  ('Round Bar 20mm', 'RB 20', 'Round Bar', '{"shape":"RB","a":20}'::jsonb),
  ('Round Bar 30mm', 'RB 30', 'Round Bar', '{"shape":"RB","a":30}'::jsonb),
  ('Equal Angle 40x40x3mm', 'EA 40x40x3', 'Equal Angle', '{"shape":"EA","a":40,"t":3}'::jsonb),
  ('Equal Angle 50x50x5mm', 'EA 50x50x5', 'Equal Angle', '{"shape":"EA","a":50,"t":5}'::jsonb),
  ('Equal Angle 80x80x6mm', 'EA 80x80x6', 'Equal Angle', '{"shape":"EA","a":80,"t":6}'::jsonb),
  ('Equal Angle 100x100x8mm', 'EA 100x100x8', 'Equal Angle', '{"shape":"EA","a":100,"t":8}'::jsonb),
  ('152x152x37', 'UC 152x152x37', 'H-Beam', '{"shape":"UC","a":152,"b":152,"kgm":37}'::jsonb),
  ('203x203x46', 'UC 203x203x46', 'H-Beam', '{"shape":"UC","a":203,"b":203,"kgm":46}'::jsonb),
  ('254x146x37KG', 'UB 254x146x37', 'I-Beam', '{"shape":"UB","a":254,"b":146,"kgm":37}'::jsonb),
  ('254x146x37', 'UB 254x146x37', 'I-Beam', '{"shape":"UB","a":254,"b":146,"kgm":37}'::jsonb),
  ('406x178x54', 'UB 406x178x54', 'I-Beam', '{"shape":"UB","a":406,"b":178,"kgm":54}'::jsonb)
on conflict (old) do update set new = excluded.new, type = excluded.type, dims = excluded.dims;

-- ============ PART 3 ============
insert into public.section_rename_map (old, new, type, dims) values
  ('406x178x60', 'UB 406x178x60', 'I-Beam', '{"shape":"UB","a":406,"b":178,"kgm":60}'::jsonb),
  ('Seamless Pipe NB20 SCH160 26.7 x 5.56', 'PIPE NB20 SCH160 26.7OD 15.58ID 5.56WT', 'Pipe', '{"shape":"PIPE","std":"SCH","nb":20,"sch":"160","od":26.7,"t":5.56}'::jsonb),
  ('Seamless Pipe NB20 SCH160 (26.7 x 5.56mm)', 'PIPE NB20 SCH160 26.7OD 15.58ID 5.56WT', 'Pipe', '{"shape":"PIPE","std":"SCH","nb":20,"sch":"160","od":26.7,"t":5.56}'::jsonb),
  ('Seamless Pipe NB25 SCH40 (33.4x4.55mm)', 'PIPE NB25 SCH80 33.4OD 24.3ID 4.55WT', 'Pipe', '{"shape":"PIPE","std":"SCH","nb":25,"sch":"80","od":33.4,"t":4.55}'::jsonb),
  ('Seamless Pipe NB40 SCH80 (48.26x5.08mm)', 'PIPE NB40 SCH80 48.3OD 38.14ID 5.08WT', 'Pipe', '{"shape":"PIPE","std":"SCH","nb":40,"sch":"80","od":48.3,"t":5.08}'::jsonb),
  ('Welded Pipe NB15 Medium (21.7x2.3mm)', 'PIPE NB15 SANS62 Medium 21.3OD 16ID 2.65WT', 'Pipe', '{"shape":"PIPE","std":"SANS62","nb":15,"cls":"Medium","od":21.3,"t":2.65}'::jsonb),
  ('80x42x6 Channel BPW', 'CC 80x42x6', 'Custom Channel', '{"shape":"CC","a":80,"b":42,"t":6}'::jsonb),
  ('120x55', 'CH 120x55', 'Taper Flange Channel', '{"shape":"CH","a":120,"b":55}'::jsonb)
on conflict (old) do update set new = excluded.new, type = excluded.type, dims = excluded.dims;

-- ============ PART 4 ============
-- The two 38.1 stock lines carried their length in the name.
update public.stock_items set length = 3.25 where main_cat = 'structural' and lower(trim(name)) = '38.10*1.60*3250mm' and coalesce(length, 0) = 0;
update public.stock_items set length = 3.3 where main_cat = 'structural' and lower(trim(name)) = '38.10*1.60*3300mm' and coalesce(length, 0) = 0;

delete from public.master_factor_items where list_name = 'sections' and trim(name) = 'Round Tube 42mm x 1.';

update public.master_factor_items f set name = m.new, type = m.type, dimensions = m.dims
from public.section_rename_map m
where f.list_name = 'sections' and lower(trim(f.name)) = lower(m.old);

insert into public.master_factor_items (id, list_name, name, factor, price, type, grade, dimensions)
select 'sec-' || md5(m.new), 'sections', m.new, 0, 0, m.type, '', m.dims
from (select distinct new, type, dims from public.section_rename_map where new = 'CH 120x55') m
where not exists (select 1 from public.master_factor_items f where f.list_name = 'sections' and f.name = m.new);

-- Rows that became the same size in the same material: keep one.
with ranked as (
  select id,
    row_number() over w as rn,
    max(factor) over (partition by lower(name), lower(coalesce(grade, ''))) as best_factor,
    max(price) over (partition by lower(name), lower(coalesce(grade, ''))) as best_price
  from public.master_factor_items
  where list_name = 'sections'
  window w as (partition by lower(name), lower(coalesce(grade, '')) order by (price > 0) desc, (factor > 0) desc, id)
)
update public.master_factor_items f set factor = r.best_factor, price = r.best_price
from ranked r where f.id = r.id and r.rn = 1 and (f.factor <> r.best_factor or f.price <> r.best_price);

delete from public.master_factor_items f
using (
  select id, row_number() over (partition by lower(name), lower(coalesce(grade, '')) order by (price > 0) desc, (factor > 0) desc, id) as rn
  from public.master_factor_items where list_name = 'sections'
) r
where f.id = r.id and r.rn > 1;

-- ============ PART 5 ============
update public.stock_items s set name = m.new from public.section_rename_map m
  where s.main_cat = 'structural' and lower(trim(s.name)) = lower(m.old);
update public.requisitions r set item_raw_name = m.new from public.section_rename_map m
  where r.main_cat = 'structural' and lower(trim(r.item_raw_name)) = lower(m.old);
update public.requisitions r set item_label = left(r.item_label, length(r.item_label) - length(m.old)) || m.new
  from public.section_rename_map m
  where r.main_cat = 'structural' and lower(r.item_label) like '% — ' || lower(m.old);
update public.job_cut_items c set section = m.new from public.section_rename_map m where lower(trim(c.section)) = lower(m.old);
update public.quote_parts p set section = m.new from public.section_rename_map m where lower(trim(p.section)) = lower(m.old);
update public.bom_parts b set section = m.new from public.section_rename_map m where lower(trim(b.section)) = lower(m.old);
update public.job_allocations a set item_name = m.new from public.section_rename_map m
  where a.main_cat = 'structural' and lower(trim(a.item_name)) = lower(m.old);
update public.usage_log u set item_name = m.new from public.section_rename_map m
  where u.main_cat = 'structural' and lower(trim(u.item_name)) = lower(m.old);

-- Section, then material: "SHS 50x50x2mm SS304" -> "SHS 50x50x2 SS304".
update public.tube_section_aliases t set section_name = m.new || substr(trim(t.section_name), length(m.old) + 1)
  from public.section_rename_map m
  where lower(trim(t.section_name)) = lower(m.old) or lower(trim(t.section_name)) like lower(m.old) || ' %';
update public.laser_programs l set material = m.new || substr(trim(l.material), length(m.old) + 1)
  from public.section_rename_map m where lower(trim(l.material)) like lower(m.old) || ' %';
update public.job_quote_items j set material_type = m.new || substr(trim(j.material_type), length(m.old) + 1)
  from public.section_rename_map m where lower(trim(j.material_type)) like lower(m.old) || ' %';

-- ============ PART 6 ============
-- The Section Types list becomes the fixed 18, in their order.
do $do$
declare
  labels text[] := array['Square Tube', 'Rectangular Tube', 'Round Tube', 'Pipe', 'Round Bar', 'Square Bar', 'Flat Bar', 'Hex Bar', 'Equal Angle', 'Unequal Angle', 'Parallel Flange Channel', 'Lipped Channel', 'Taper Flange Channel', 'Custom Channel', 'I-Beam', 'H-Beam', 'IPE Beam', 'Tee'];
  i int;
begin
  delete from public.master_string_lists where list_name = 'sectionTypes' and value <> all (labels);
  for i in 1 .. array_length(labels, 1) loop
    insert into public.master_string_lists (id, list_name, value, sort_order)
    select 'st-' || md5(labels[i]), 'sectionTypes', labels[i], i
    where not exists (select 1 from public.master_string_lists where list_name = 'sectionTypes' and value = labels[i]);
    update public.master_string_lists set sort_order = i where list_name = 'sectionTypes' and value = labels[i];
  end loop;
end $do$;
